package org.eso.ias.prototype.compele

import org.eso.ias.prototype.transfer.JavaTransfer
import org.eso.ias.prototype.input.Identifier
import org.eso.ias.prototype.input.HeteroInOut
import scala.collection.mutable.HashMap
import org.eso.ias.prototype.input.AckState
import scala.collection.mutable.{Map => MutableMap }
import org.eso.ias.prototype.input.AlarmValue
import org.eso.ias.prototype.input.java.IASTypes
import org.eso.ias.prototype.transfer.ScalaTransfer

/**
 * It consists of a state (<code>ASCState</code>) and methods
 * to proceed to the next state.
 * 
 * The output is updated each time one of the input is updated:
 * a script checks the values of the inputs and generate the output.
 * It can be a AlarmValue but also a MonitorPoint[A] if the scripts
 * result in a value of type A (used to implement
 * so called synthetic parameters)
 * 
 * The output of a Component can, in turn, be the input 
 * of another Component.
 * 
 * A <code>AlarmSystemComponent</code> represents the state of the ASC
 * at a given point in time. It can be considered as a snapshot of the ASC
 * for the given inputs and output generated by running the script.
 * As such it can be used also offline to reproduce the state of the system
 * for debugging or simulation purposes.
 * 
 * <EM>Functioning</EM>
 * The ASC has an output, produced by the actualInputs that is refreshed at 
 * a given time interval.
 * Changes in the inputs are temporarily stored in the newInputs map.
 * When the refresh rate elapses the new value output with its validity is calculated 
 * from the newly received inputs (newInputs) and a new AlarmSystemComponent
 * is built.
 * 
 * @param ident: The unique ID of this Component
 * @param out: The the output generated by this Component
 *             after applying the script to the inputs
 *             It can or cannot be an AlarmValue
 * @param requiredInputs: The IDs of the inputs that this component
 *                        needs to generate the output. The list does not change
 *                        during the life time of the component.
 * @param actualInputs: The list of monitor points in input that generated the actual output
 * @param script: The script that manipulated the inputs and generate the output
 * @param newInputs: the map with the value of the monitor points in input
 *                   received after the last update of the output  
 * @see AlarmSystemComponentBase, ComputingElementState
 * 
 * @author acaproni
 */
class ComputingElement(
    ident: Identifier,
    out: HeteroInOut,
    requiredInputs: List[String],
    actualInputs: MutableMap[String, HeteroInOut],
    script: String,
    newInputs: MutableMap[String, HeteroInOut] =  new HashMap[String,HeteroInOut]()) 
extends ComputingElementBase(ident,out,requiredInputs.sorted,actualInputs,script,newInputs) 
with JavaTransfer with ScalaTransfer {
  
  /**
   * @return true if this component produces a synthetic parameter instead of an alarm
   * @see isAlarmComponent
   */
  def isSyntheticParameterComponent = out.iasType!=IASTypes.ALARM
  
  /**
   * @return true if this component generates an alarm
   * @see #isSyntheticParameterComponent
   */
  def isAlarmComponent = out.iasType!=IASTypes.ALARM
  
  /**
   * A monitor point changed: it is stored in the map
   * ready to be evaluated when refreshing the value
   * of the output 
   * 
   * @param mp: The new value of a monitor point in input
   */
  def inputChanged(mp: Some[HeteroInOut]) {
    if (!requiredInputs.contains(mp.get.id.id.get)) {
      throw new IllegalStateException("Trying to pass a MP to a component that does not want it: "+mp.get.id.id.get+" not in "+requiredInputs.mkString(", "))
    }
    newInputs.synchronized {
      newInputs(mp.get.id.id.get)=mp.get
    }
  }
  
  /**
   * Get the alarm value of AlarmValue of the output.
   * 
   * @throws IllegalStateException: If the value of the output is None 
   *         or has a wrong type.
   */
  private def getOutAlarmValue: AlarmValue = {
    // Check if the value of the output is None i.e. the output has not yet 
    // been initialized.
    //
    // Having a output with a value of None should never happen because its value is
    // updated depending on the value of the inputs
    if (output.actualValue== None) {
      throw new IllegalStateException("Trying get an alarm but the value is None (alarm ID "+output.id+")") 
    }
    if (output.iasType!=IASTypes.ALARM) {
      throw new IllegalStateException("Trying to get an alarm but the value has IAS type "+output.iasType+" (alarm ID "+output.id+")")
    }
    val value: Any = output.actualValue.get.value
    
    if (! value.isInstanceOf[AlarmValue]) {
      throw new IllegalStateException("Type mismatch: IAS type is "+output.iasType+" but the class of the valueis "+value.getClass()+" (alarm ID "+output.id+")")
    }
    value.asInstanceOf[AlarmValue]
  }
  
  /**
   * Shelve the output in response to an operator action.
   * 
   * This action is possible only if the output is a MonitorPoint[AlarmValue].
   * It is not needed to recalculate the output from the inputs when shelving an alarm.
   * 
   * @param newShelveState: True to shelve the alarm; false otherwise 
   * @return The ASCE shelved
   */
  def shelve(newShelveState: Boolean) = {
    
    val value: AlarmValue = getOutAlarmValue
    if (value.shelved==newShelveState) this // No change
    val newValue = value.shelve(newShelveState)
    
    output=output.updateValue(newValue)    
  }
  
  /**
   * Acknowledge the output in response to an operator action.
   * 
   * This action is possible only if the output is a MonitorPoint[AlarmValue].
   * It is not needed to recalculate the output from the inputs when shelving an alarm.
   * 
   * @return The ASCE acknowledged
   */
  def ack() = {
    
    val value: AlarmValue = getOutAlarmValue
    if (value.acknowledgement==AckState.Acknowledged) this // No change
    val newValue = value.acknowledge()
    
    output=output.updateValue(newValue)
  }
  
}